apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  labels:
    fluentbit.gardener/type: "seed"
  name: cloud-controller-manager-cloud-provider-equinix-metal
spec:
  filters:
  - parser:
      keyName: log
      parser: kube-apiserver-parser
      reserveData: true
  match: kubernetes.*cloud-controller-manager*cloud-provider-equinix-metal*
---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  labels:
    fluentbit.gardener/type: "seed"
  name: machine-controller-manager-machine-controller-manager-provider-equinix-metal
spec:
  filters:
  - parser:
      keyName: log
      parser: kube-apiserver-parser
      reserveData: true
  match: kubernetes.*machine-controller-manager*machine-controller-manager-provider-equinix-metal*
---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  labels:
    fluentbit.gardener/type: "seed"
  name: machine-controller-manager-equinix-metal-machine-controller-manager
spec:
  filters:
  - parser:
      keyName: log
      parser: kube-apiserver-parser
      reserveData: true
  match: kubernetes.*machine-controller-manager*equinix-metal-machine-controller-manager*
---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  labels:
    fluentbit.gardener/type: "seed"
  name: modify-provider-equinix-metal
spec:
  filters:
  - modify:
      conditions:
        - keyValueMatches:
            tag: ^kubernetes\.var\.log\.containers\.(cloud-controller-manager-.+?_.+?_cloud-provider-equinix-metal)
      rules:
        - add:
            __gardener_multitenant_id__: operator;user
  - modify:
      conditions:
        - keyValueMatches:
            tag: ^kubernetes\.var\.log\.containers\.machine-controller-manager-.+?_.+?_(machine-controller-manager-provider-equinix-metal|equinix-metal-machine-controller-manager)
      rules:
        - add:
            __gardener_multitenant_id__: operator;user
  match:  kubernetes.*
